server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommercemicroservices_authentication
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 604800000
jwt:
  secret: "daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb"

logging:
 level:
  org:
   hibernate: DEBUG

#debug: true
