server:
  port: 8081
  error:
    include-message: always

rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommercemicroservices_authentication
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth-server
          jwk-set-uri: http://localhost:8081/auth-server/oauth2/jwks
        provider:
          authblabla2:
            issuer-uri: http://localhost:8086/auth-server
  application:
    name: authentication-service


app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 604800000

jwt:
  secret: "daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb"

logging:
 level:
  org:
   hibernate: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#debug: true
