version: "3"
services:
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#  redis:
#    image: "redis:latest"
#    ports:
#      - "6379:6379"
#    volumes:
#      - redis-data:/data
#
#  elasticsearch:
#    image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.0"
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9200:9200"
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data
#
#  mongo:
#    image: "mongo:latest"
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongodb-data:/data/db
#
#  mysql:
#    image: "mysql:latest"
#    ports:
#      - "3306:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: mohamed
#      MYSQL_DATABASE: mohameddatabase
#      MYSQL_USER: mohamedadel
#      MYSQL_PASSWORD: mohamedadel
#    volumes:
#      - mysql-data:/var/lib/mysql

#volumes:
#  rabbitmq-data:
#  redis-data:
#  elasticsearch-data:
#  mongodb-data:
#  mysql-data: