jenkins:
  systemMessage: "Welcome to Jenkins!"
  numExecutors: 2
  clouds:
    - docker:
        name: "Docker"
        dockerApi:
          dockerHost:
            uri: "tcp://docker-host:2376"
            credentialsId: "docker-credentials-id"
  globalLibraries:
    - name: "shared-libraries"
      retriever:
        modernSCM:
          scm:
            git:
              remote: "https://github.com/your-username/your-shared-libraries.git"
              credentialsId: "github-credentials-id"
              branch: "main"
  tool:
    docker:
      installations:
        - name: "Docker"
          home: "/usr/bin/docker"
    maven:
      installations:
        - name: "Maven"
          home: "/usr/local/bin/mvn"
  jobs:
    - script: >
        pipelineJob('microservice-e-commerce') {
          definition {
            cpsScm {
              scm {
                git {
                  remote {
                    url('https://github.com/your-username/your-project.git')
                  }
                  branch('main')
                  extensions {
                    cleanBeforeCheckout()
                  }
                }
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
