spring:
  application:
    name: eureka-naming-service
  cloud:
    config:
      import-check:
        enabled: true

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost